# Live Trading Configuration
mode: live

# Market Data
market_data:
  provider: zerodha
  instruments:
    nifty_futures:
      - 256265  # Current month
      - 256521  # Next month
    banknifty_futures:
      - 260105  # Current month  
      - 260361  # Next month
  subscription_mode: full  # full, ltp, quote

# Strategies
strategies:
  mean_reversion:
    enabled: true
    lookback_period: 20
    z_score_threshold: 2.0
    position_size: 25  # lots
    max_positions: 2
    
  momentum:
    enabled: true
    fast_ma: 10
    slow_ma: 30
    position_size: 25
    max_positions: 2
    
  stat_arb:
    enabled: true
    lookback_period: 60
    correlation_threshold: 0.8
    position_size: 50
    max_positions: 1

# Risk Management
risk:
  max_position_size: 100  # lots per instrument
  max_notional_per_order: 1000000  # Rs 10L
  max_daily_loss: 50000  # Rs 50K
  max_orders_per_minute: 60
  price_collar_pct: 0.05  # 5%
  position_concentration_limit: 0.3  # 30% of portfolio

# Execution
execution:
  default_product_type: MIS  # Intraday
  default_order_type: LIMIT
  slippage_tolerance: 0.001  # 0.1%
  max_order_retry: 3
  retry_delay_ms: 100

# Portfolio
portfolio:
  initial_cash: 1000000  # Rs 10L
  margin_buffer: 0.2  # 20% margin buffer
  
# Infrastructure
redis:
  url: redis://redis:6379
  stream_maxlen: 10000
  cache_ttl: 300

postgres:
  url: postgresql://trader:password@postgres:5432/trading_system
  pool_size: 10
  max_overflow: 20

# Monitoring
monitoring:
  metrics_port: 8000
  health_check_interval: 30
  log_level: INFO
  
alerts:
  slack_webhook: ${SLACK_WEBHOOK_URL}
  email_recipients: 
    - trader@example.com
